[workspace]
resolver = "3"
members = ["pyo3-rkshare","rkshare", "rkshare-server", "rkshare-sse", "rkshare-szse", "rkshare-xq"]

[workspace.dependencies]
anyhow = "1.0.98"
arrow = "55.2.0"
reqwest = { version = "0.12.22", features = ["json"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = { version = "1.0.140", features = ["raw_value"] }
tokio = { version = "1.46.1", features = ["full"] }
url = "2.5.4"
