from arro3.core import RecordBatch

def stock_sse_summary() -> RecordBatch: ...
def stock_sse_deal_daily(date: str) -> RecordBatch: ...
def stock_szse_summary(date: str) -> RecordBatch: ...
def stock_szse_area_summary(date: str) -> RecordBatch: ...
